-- Tabela de Usuários (Atende as Telas: Login, Cadastro e Dashboard)
CREATE TABLE TB_USUARIOS (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    total_kg_reciclado NUMBER(10,2) DEFAULT 0,
    total_co2_evitado NUMBER(10,2) DEFAULT 0,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

