-- Tabela de Ecopontos (Atende a Tela: Detalhes e Integração com Maps)
CREATE TABLE TB_ECOPONTOS (
    id_ecoponto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    endereco VARCHAR2(255) NOT NULL,
    latitude NUMBER(10, 8),
    longitude NUMBER(11, 8),
    horario_funcionamento VARCHAR2(100),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
