-- Tabela de Materiais (Atende as Telas: Busca e Detalhes do Material)
CREATE TABLE TB_MATERIAIS (
    id_material NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50),
    risco_ambiental CLOB,
    como_descartar CLOB,
    is_perigoso NUMBER(1) CHECK (is_perigoso IN (0, 1)),
    is_reciclavel NUMBER(1) CHECK (is_reciclavel IN (0, 1)),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);