-- Tabela de Agendamentos (Atende a Tela: Dashboard - Próxima Coleta)
CREATE TABLE TB_AGENDAMENTOS (
    id_agendamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_material NUMBER NOT NULL,
    id_ecoponto NUMBER NOT NULL,
    data_coleta TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDENTE',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES TB_USUARIOS(id_usuario),
    CONSTRAINT fk_material FOREIGN KEY (id_material) REFERENCES TB_MATERIAIS(id_material),
    CONSTRAINT fk_ecoponto FOREIGN KEY (id_ecoponto) REFERENCES TB_ECOPONTOS(id_ecoponto)
);